name: Application CI/CD

on:
  workflow_dispatch:    # Manually trigger the workflow from GitHub UI
  push:
    branches: 
        - main
    paths: ["app/**"]
  pull_request:
    branches:
        - main
    paths: ["app/**"]

permissions:
  id-token: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      aws_id: ${{vars.AWS_ID}}
      ec2_hostname: ${{vars.EC2_HOSTNAME}}   ##change this to your instance id
    steps:
    - uses: actions/checkout@v5

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@main
      with:
        role-to-assume: arn:aws:iam::${{env.aws_id}}:role/nodejsappdev
        aws-region: us-east-1

    - name: debugging path
      shell: bash
      run: |
        cd app
        ls -la
  
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build, tag, and push docker image to Amazon ECR
      env:
        REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        REPOSITORY: ksn-nodejs-repo       ##change this to your repo name
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build app/ -t $REGISTRY/$REPOSITORY:$IMAGE_TAG
        docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
        echo "IMAGE $IMAGE_TAG is pushed to $ECR_REGISTRY/$ECR_REPOSITORY"
        echo "image_tag=$IMAGE_TAG" 
        echo "full_image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"

    - name: SSH into EC2 instance and run commands
      uses: appleboy/ssh-action@v1
      env:
        REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        REPOSITORY: ksn-nodejs-repo       ##change this to your repo name
        IMAGE_TAG: ${{ github.sha }}
      with:
        host: ${{env.ec2_hostname}}   ##change this to your instance public dns
        username: ec2-user
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin $REGISTRY/$REPOSITORY
          docker pull $REGISTRY/$REPOSITORY:$IMAGE_TAG
          docker stop nodejsapp || true
          docker rm nodejsapp || true
          docker run -d -p 80:8080 --name nodejsapp $REGISTRY/$REPOSITORY:$IMAGE_TAG